### ISSUE TITLE
Failed Deployment on Vercel 

### ISSUE THREAD

**Issue by ileana-pr** [ileana-pr/Ask_Doc#1]
See log file: https://vercel.com/ileanas-projects/ask_doc/4pteB2BMDLzky8ZGkEz28yk59Ubw?filter=errors

**Comment by ileana-pr** [comment]
attaching Vercel deployment log.txt 
[log.txt](https://github.com/user-attachments/files/16614044/log.txt)

**Comment by MatheusDaros** [comment]
Hey @ileana-pr looking at the logs we have some kind of errors like these: `Module not found: Can't resolve 'ai/rsc'`.
Now looking at your `package.json` I see this list of dependencies:

```
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.2.5"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "eslint": "^8",
    "eslint-config-next": "14.2.5"
  }
```

It seems you did not install the dependencies to this project. Is that correct?

**Comment by ileana-pr** [comment]
Hello @MatheusDaros, I reviewed the steps in the slides and I am sure I completed each one. The app works well on my end. I believe I have found the folder you referenced in the error. Here is a screenshot of my files. 
![Screenshot 2024-08-15 135755](https://github.com/user-attachments/assets/536dc63d-8ea2-4379-9dbd-b7d1d5866cac)

**Comment by MatheusDaros** [comment]
Yes this screenshot is from your `node_modules` folder. But that folder should never be uploaded to git.
In order for the project to work correctly, not only the required dependencies should be in the `node_modules` folder, but also they should be listed in the `package.json` file, in the root of your project.

**Comment by ileana-pr** [comment]
Success.. I was able to correctly install dependencies.. however now looks like I am running into error generating pages. Attached new deployment log. Thank you. 
[20240816log.txt](https://github.com/user-attachments/files/16643151/20240816log.txt)

**Comment by MatheusDaros** [comment]
I'm having this error when I click the link:

```
<Error>
<Code>InvalidRange</Code>
<Message>The requested range is not satisfiable</Message>
<RangeRequested>bytes=0-10485759</RangeRequested>
<ActualObjectSize>0</ActualObjectSize>
<RequestId>A2TR48N4C1C2TTAH</RequestId>
<HostId>
nuhj5YBO+ckE0doqQPioLUcZndMJOS7mZqnhyAFyUaOFkel++yoGDf/dQrj0E8giEuR1VYKYSr4=
</HostId>
</Error>
```

Maybe you could paste the contents of the log here as plain text?

**Comment by ileana-pr** [comment]
My apologies.. I thought it would attach the .txt file. Here is copy pasta: 

[22:16:34.740] Running build in Washington, D.C., USA (East) – iad1
[22:16:34.946] Cloning github.com/ileana-pr/Ask_Doc (Branch: main, Commit: 456810f)
[22:16:34.963] Skipping build cache, deployment was triggered without cache.
[22:16:42.959] Cloning completed: 8.007s
[22:16:47.846] Running "vercel build"
[22:16:48.791] Vercel CLI 36.0.0
[22:16:49.506] WARNING: You should not upload the `.next` directory.
[22:16:49.514] Installing dependencies...
[22:16:54.020] 
[22:16:54.021] added 2 packages in 4s
[22:16:54.021] 
[22:16:54.021] 140 packages are looking for funding
[22:16:54.021]   run `npm fund` for details
[22:16:54.035] Detected Next.js version: 14.2.5
[22:16:54.038] Detected `package-lock.json` generated by npm 7+
[22:16:54.039] Running "npm run build"
[22:16:54.168] 
[22:16:54.169] > ask_doc@0.1.0 build
[22:16:54.169] > next build
[22:16:54.169] 
[22:16:55.218] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[22:16:55.218] This information is used to shape Next.js' roadmap and prioritize features.
[22:16:55.218] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[22:16:55.219] https://nextjs.org/telemetry
[22:16:55.219] 
[22:16:55.280]   ▲ Next.js 14.2.5
[22:16:55.280] 
[22:16:55.351]    Creating an optimized production build ...
[22:17:09.252]  ✓ Compiled successfully
[22:17:09.253]    Linting and checking validity of types ...
[22:17:13.528]    Collecting page data ...
[22:17:14.963]    Generating static pages (0/5) ...
[22:17:15.100]    Generating static pages (1/5) 
[22:17:15.101] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.101]     at exports.useContext (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:495)
[22:17:15.101]     at h (/vercel/path0/.next/server/pages/_error.js:1:5992)
[22:17:15.104]     at Wc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[22:17:15.104]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[22:17:15.104]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[22:17:15.104]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.106]     at bd (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
[22:17:15.106]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
[22:17:15.106]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.107]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[22:17:15.107] 
[22:17:15.107] Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
[22:17:15.108] 
[22:17:15.108] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.108]     at exports.useContext (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:495)
[22:17:15.108]     at h (/vercel/path0/.next/server/pages/_error.js:1:5992)
[22:17:15.110]     at Wc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[22:17:15.110]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[22:17:15.111]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[22:17:15.111]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.111]     at bd (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
[22:17:15.111]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
[22:17:15.111]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.112]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[22:17:15.123]    Generating static pages (2/5) 
[22:17:15.124]    Generating static pages (3/5) 
[22:17:15.124] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.124]     at exports.useContext (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:495)
[22:17:15.125]     at h (/vercel/path0/.next/server/pages/_error.js:1:5992)
[22:17:15.125]     at Wc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[22:17:15.125]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[22:17:15.125]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[22:17:15.125]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.125]     at bd (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
[22:17:15.126]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
[22:17:15.126]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.126]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[22:17:15.126] 
[22:17:15.126] Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
[22:17:15.126] 
[22:17:15.127] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.127]     at exports.useContext (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:495)
[22:17:15.127]     at h (/vercel/path0/.next/server/pages/_error.js:1:5992)
[22:17:15.127]     at Wc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[22:17:15.127]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[22:17:15.127]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[22:17:15.128]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.128]     at bd (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
[22:17:15.128]     at Z (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
[22:17:15.128]     at $c (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
[22:17:15.128]     at Zc (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[22:17:15.294] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.294]     at t.useContext (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
[22:17:15.294]     at d (/vercel/path0/.next/server/chunks/99.js:1:21717)
[22:17:15.294]     at h (/vercel/path0/.next/server/chunks/99.js:1:13638)
[22:17:15.294]     at nj (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[22:17:15.295]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.295]     at nI (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[22:17:15.295]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546) {
[22:17:15.295]   digest: '2493133643'
[22:17:15.295] }
[22:17:15.295] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.295]     at t.useContext (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
[22:17:15.295]     at d (/vercel/path0/.next/server/chunks/99.js:1:21717)
[22:17:15.295]     at h (/vercel/path0/.next/server/chunks/99.js:1:13638)
[22:17:15.295]     at nj (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[22:17:15.295]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.295]     at nI (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[22:17:15.295]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.295] 
[22:17:15.295] Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
[22:17:15.295] 
[22:17:15.295] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.295]     at t.useContext (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
[22:17:15.295]     at d (/vercel/path0/.next/server/chunks/99.js:1:21717)
[22:17:15.295]     at h (/vercel/path0/.next/server/chunks/99.js:1:13638)
[22:17:15.295]     at nj (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[22:17:15.295]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.295]     at nI (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
[22:17:15.295]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[22:17:15.295]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.486] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.487]     at t.useContext (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
[22:17:15.487]     at d (/vercel/path0/.next/server/chunks/99.js:1:21717)
[22:17:15.487]     at h (/vercel/path0/.next/server/chunks/99.js:1:13638)
[22:17:15.487]     at nj (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[22:17:15.487]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[22:17:15.488]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.488]     at nI (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
[22:17:15.488]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
[22:17:15.488]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[22:17:15.488]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546) {
[22:17:15.488]   digest: '2493133643'
[22:17:15.488] }
[22:17:15.489] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.489]     at t.useContext (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
[22:17:15.489]     at d (/vercel/path0/.next/server/chunks/99.js:1:21717)
[22:17:15.489]     at h (/vercel/path0/.next/server/chunks/99.js:1:13638)
[22:17:15.489]     at nj (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[22:17:15.489]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[22:17:15.489]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.489]     at nI (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
[22:17:15.490]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
[22:17:15.490]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[22:17:15.490]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.490] 
[22:17:15.490] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[22:17:15.490] 
[22:17:15.490] TypeError: Cannot read properties of null (reading 'useContext')
[22:17:15.490]     at t.useContext (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
[22:17:15.491]     at d (/vercel/path0/.next/server/chunks/99.js:1:21717)
[22:17:15.491]     at h (/vercel/path0/.next/server/chunks/99.js:1:13638)
[22:17:15.491]     at nj (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[22:17:15.491]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[22:17:15.491]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.491]     at nI (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
[22:17:15.491]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
[22:17:15.492]     at nM (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[22:17:15.492]     at nN (/usr/local/share/.config/yarn/global/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[22:17:15.492]  ✓ Generating static pages (5/5)
[22:17:15.593] 
[22:17:15.595] > Export encountered errors on following paths:
[22:17:15.598] 	/_error: /404
[22:17:15.598] 	/_error: /500
[22:17:15.599] 	/_not-found/page: /_not-found
[22:17:15.599] 	/page: /
[22:17:15.629] Error: Command "npm run build" exited with 1
[22:17:16.348]

**Comment by MatheusDaros** [comment]
According to the error logs, it seems like some [prerender error](https://nextjs.org/docs/messages/prerender-error) in some pages (`/404`, `/500`, `/` and `/_not-found`).
Did you code these pages yourself?
Or maybe you should be using the `App Router` instead of this `actions.ts`?

**Comment by ileana-pr** [comment]
I pasted the code from this tutorial in `page.tsx` and `actions.ts` (https://sdk.vercel.ai/examples/next-app/chat/stream-chat-completion) according to the instructions in the course, and only edited a few minor adjustments to the fonts, colors, etc, to make the page show up correctly. Thank you for directing me to this info.. I will learn more about the `App Router` and see if that works.

**Comment by MatheusDaros** [comment]
I see
The example is using the `Pages Router`, so if you try [this example](https://sdk.vercel.ai/examples/next-pages/chat/stream-chat-completion) instead it should work.

**Comment by ileana-pr** [comment]
Success! I fixed by removing node_modules and running -npm run build- .You can access the app here: https://ask-doc-five.vercel.app/ 
Will work on improving UI.
